### PR TITLE
Doc Updates

### PR DESCRIPTION
**Pull request by bengl**
* man page (modified README slightly so it can be generated from it)
* help command now powered by `yargs`

### CODE REVIEW

**Comment by davglass** [comment]
:+1:  Merge it!

**Comment by davglass** [comment]
FYI:

```
$ npm owner ls registry-static
davglass
bengl
```

**Comment by bengl** [comment]
Awaiting https://github.com/npm/npm/pull/7299

**Comment by bengl** [comment]
Screw it, not waiting. Once npm is fixed the man page will work on next install.

**Pull request merged**
