### PR TITLE
do not allow deletions of individual versions

### PR DESCRIPTION
**Pull request by bengl**
reason: http://blog.npmjs.org/post/141577284765/kik-left-pad-and-npm

### CODE REVIEW

**Comment by drewfish** [comment]
LGTM

**Comment by davglass** [comment]
:+1:

**Comment by bengl** [comment]
@drewfish @davglass I added two extra tests to make sure it doesn't barf on bad data, since, as we know, bad data can and does happen.

**Comment by drewfish** [comment]
+yep

**Comment by davglass** [comment]
:+1: This process does protect against unpublished modules, but it doesn't stop new updates to an unpublished module. What if the next step is to add a check for the `unpublished` key and not allow further updates?

**Pull request merged**
