### PR TITLE
remove check & sync

### PR DESCRIPTION
**Pull request by bengl**
`check` and `sync` aren't particularly useful, and are a pain to test/maintain/etc., so nuking them.

**major** change

### CODE REVIEW

**Comment by davglass** [comment]
:+1:

**Comment by drewfish** [comment]
+1

**Comment by krotscheck** [comment]
Is there any other way to perform diagnostics on my mirror data?

**Comment by davglass** [comment]
@krotscheck The check command that was in there was not very good at what it did. After we clean this up we will be looking into ways to do this properly. I think @bengl might have an idea on how we can do this more performant.

**Comment by bengl** [comment]
@krotscheck The best way is always to restart at sequence 0. This, of course, isn't always practical.

Maybe we can leave it in there until a suitable replacement is built?

**Comment by bengl** [comment]
@krotscheck also, which pieces of data are you looking for that are useful in `check`? It might be best to recreate them in new code.

**Comment by krotscheck** [comment]
Well, I'm not using it yet ( https://review.openstack.org/#/c/235617/ needs to merge, and I'm on vaca until monday), however we provide ops for all of OpenStack, and the ability to quickly diagnose why a particular package isn't resolving (and repair it) would be nice. Crazy validation of the entire mirror is not really necessary, it's more a "Hey one of the builds is breaking because package X is borked, can we go twiddle some bits" need.

**Comment by davglass** [comment]
Ah, well that's easy. The `one` command can do that.. `registry-static --config ... --one <name of package>` and it will only sync that package. You can also do it from the `repl` if you use that. (@bengl please correct my command if that is wrong)

**Comment by krotscheck** [comment]
And this will teach me to read the documentation :). Thanks!

**Comment by bengl** [comment]
Yeah `one` is definitely what you're looking for. I use it pretty often.

Also since disk space is mentioned in that PR... count on a TB. That should cover your for about the next year or so.

**Comment by bengl** [comment]
Gonna go ahead and merge this.

**Pull request merged**
